<a href="https://colab.research.google.com/github/NaraineSurya/Pytorch-Basics/blob/master/Auto%20Grad%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
x = torch.randn(3)
x.shape

torch.Size([3])

In [5]:
# Tensors with no requires gradient
x = torch.randn(3, requires_grad = False)
print(x)

y= x + 2
print(y)

z = y * y * 2
print(z)

tensor([ 0.5327, -0.0997,  0.1249])
tensor([2.5327, 1.9003, 2.1249])
tensor([12.8292,  7.2222,  9.0306])


# **Gradients can be calculated only for scalar outputs**

In [7]:
# Tensors with requires_ grad = True
x = torch.randn(3, requires_grad = True)
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)

# Calculating the gradients with the scalar value (mean)
z = z.mean()
print(z)

z.backward() # This line is used to calculate the gradients in the network dz/dx
print(x.grad) # This will show the gradient value of x

tensor([-0.6474,  1.0160,  0.1497], requires_grad=True)
tensor([1.3526, 3.0160, 2.1497], grad_fn=<AddBackward0>)
tensor([ 3.6590, 18.1920,  9.2427], grad_fn=<MulBackward0>)
tensor(10.3646, grad_fn=<MeanBackward0>)
tensor([1.8035, 4.0213, 2.8663])


# **Calculating Gradient for a vector**

In [11]:
# Calculating gradients with the vectors
x = torch.randn(3, requires_grad = True)
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)

z.backward() # This line will produce error because gradients can calculated only for scalar values not for vectors, matrices or tensors
# If you need to clarify this use this given link why it needs to be scalar ??
# https://discuss.pytorch.org/t/could-loss-function-output-a-vector-instead-of-a-scalar/122084
# https://pytorch.org/docs/main/generated/torch.autograd.backward.html#torch.autograd.backward
print(x.grad)

tensor([ 0.5236,  0.2007, -0.0063], requires_grad=True)
tensor([2.5236, 2.2007, 1.9937], grad_fn=<AddBackward0>)
tensor([12.7372,  9.6865,  7.9497], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

# **Calculating Gradient with a vector using Jacobian vector product**

In [4]:
# We can use vector jacobian product to get the gradient using the vector v
x = torch.randn(3, requires_grad = True)
print(x)

y = x + 2
print(y)

z = y * y * 2
print(z)

v = torch.tensor([0.1, 0.11, 0.001], dtype=torch.float32)
z.backward(v) # Now we can calculate using the vector jacobian product to calculate the gradient
print(x.grad)


tensor([-0.8866,  1.3890, -1.0386], requires_grad=True)
tensor([1.1134, 3.3890, 0.9614], grad_fn=<AddBackward0>)
tensor([ 2.4793, 22.9702,  1.8485], grad_fn=<MulBackward0>)
tensor([0.4454, 1.4911, 0.0038])


# **Making Requires_Grad False**

In [6]:
x = torch.randn(3, requires_grad=True)
print(x)
x.requires_grad_(False) #Inplace Making of gradients to false
print(x)

tensor([-0.0757,  0.0392, -1.2966], requires_grad=True)
tensor([-0.0757,  0.0392, -1.2966])


In [10]:
x = torch.randn(4, requires_grad=True)
# print(x)
y = x.detach() #This will detach the tensor from the gradients being True
print(x)
print(y)

tensor([-0.2615, -1.7548, -0.4787, -0.5128], requires_grad=True)
tensor([-0.2615, -1.7548, -0.4787, -0.5128])


In [16]:
x = torch.randn(6, requires_grad=True)
y = torch.ones(6, requires_grad=True)
print(x)
print(y)

with torch.no_grad():
  z = x + y
  print(z)

tensor([ 1.5608,  0.3635,  0.7285, -1.9027, -0.6407, -0.1502],
       requires_grad=True)
tensor([1., 1., 1., 1., 1., 1.], requires_grad=True)
tensor([ 2.5608,  1.3635,  1.7285, -0.9027,  0.3593,  0.8498])
