<a href="https://colab.research.google.com/github/NaraineSurya/Pytorch-Basics/blob/master/Tensor%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensor Basics**

In [1]:
import torch

In [2]:
# Empty tensor
x = torch.empty(3)
x

tensor([-1.4519e+26,  4.3597e-41, -1.4519e+26])

In [3]:
# mpty Tensor in 3-D shape
x = torch.empty((3,2,2), dtype=torch.float64)
print(x)
print(x.shape)
print(x.dtype)

tensor([[[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00, 6.6023e-310],
         [6.6023e-310,  0.0000e+00]]], dtype=torch.float64)
torch.Size([3, 2, 2])
torch.float64


In [4]:
# Tensor with ones
x = torch.ones((3,2))
print(x)
print(x.size())

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.Size([3, 2])


In [5]:
# Tensor with zeros
torch.zeros((4,5), dtype=torch.int64)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [6]:
x = torch.rand((2, 2))
y = torch.randn((2, 2))
print(x)
print(y)

tensor([[0.0773, 0.3594],
        [0.5635, 0.7530]])
tensor([[ 1.0135,  1.7773],
        [ 0.5454, -0.8101]])


# **Arithmetic Operations**

In [7]:
x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[11,22,33], [44,55,66]])

print(x)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[11, 22, 33],
        [44, 55, 66]])


In [8]:
# Adding Tensors
z = x + y
print(z)
print(torch.add(x, y))
y.add_(x) #Inplace Addition in the tensor
print(y)

tensor([[12, 24, 36],
        [48, 60, 72]])
tensor([[12, 24, 36],
        [48, 60, 72]])
tensor([[12, 24, 36],
        [48, 60, 72]])


In [9]:
# Subracting Tensors

x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[11,22,33], [44,55,66]])

z = x - y
print(z)
print(torch.sub(x, y))
y.sub_(x) # Inplace subtraction in the tensor y
print(y)

tensor([[-10, -20, -30],
        [-40, -50, -60]])
tensor([[-10, -20, -30],
        [-40, -50, -60]])
tensor([[10, 20, 30],
        [40, 50, 60]])


In [10]:
# Multiplying Tensors

x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[11,22,33], [44,55,66]])

z = x * y
print(z)
print(torch.mul(x, y))
print(y.mul_(x))

tensor([[ 11,  44,  99],
        [176, 275, 396]])
tensor([[ 11,  44,  99],
        [176, 275, 396]])
tensor([[ 11,  44,  99],
        [176, 275, 396]])


In [11]:
# Dividing Tensors

x = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
y = torch.tensor([[11,22,33], [44,55,66]], dtype=torch.float32)

z = x / y
print(z)
print(torch.div(x, y))
print(x.div_(y))

tensor([[0.0909, 0.0909, 0.0909],
        [0.0909, 0.0909, 0.0909]])
tensor([[0.0909, 0.0909, 0.0909],
        [0.0909, 0.0909, 0.0909]])
tensor([[0.0909, 0.0909, 0.0909],
        [0.0909, 0.0909, 0.0909]])


# **Tensor Indexing**

In [12]:
x = torch.rand((5,3))
x

tensor([[0.6332, 0.8072, 0.1458],
        [0.3732, 0.6034, 0.1955],
        [0.8208, 0.3907, 0.9344],
        [0.4017, 0.4815, 0.8401],
        [0.0071, 0.8126, 0.9625]])

In [13]:
x[1, 2]

tensor(0.1955)

In [14]:
x[1: ]

tensor([[0.3732, 0.6034, 0.1955],
        [0.8208, 0.3907, 0.9344],
        [0.4017, 0.4815, 0.8401],
        [0.0071, 0.8126, 0.9625]])

In [15]:
x[4, -1]

tensor(0.9625)

# **Reshaping Tensors**

In [16]:
x = torch.rand((4,2))
x

tensor([[0.4474, 0.7959],
        [0.5715, 0.1486],
        [0.0018, 0.0068],
        [0.9148, 0.9117]])

In [17]:
# View Function is used for reshaping the tensors
print(x.view(1, -1))

tensor([[0.4474, 0.7959, 0.5715, 0.1486, 0.0018, 0.0068, 0.9148, 0.9117]])


In [18]:
print(x.view(2,2,2))

tensor([[[0.4474, 0.7959],
         [0.5715, 0.1486]],

        [[0.0018, 0.0068],
         [0.9148, 0.9117]]])


In [19]:
print(x.view(8, -1))

tensor([[0.4474],
        [0.7959],
        [0.5715],
        [0.1486],
        [0.0018],
        [0.0068],
        [0.9148],
        [0.9117]])


# **Tensor Type Conversion**

In [20]:
import numpy as np

a = torch.ones((2,4), dtype=torch.int64)
print(a)
b = a.numpy()
print(b)

# If torch is on cpu then numpy array as well as the torch tensor will share the same memory location

# If add a it will add it to b too
a.add_(1)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
[[1 1 1 1]
 [1 1 1 1]]
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])
[[2 2 2 2]
 [2 2 2 2]]


In [21]:
a = np.ones((4,3), dtype='int32')
b = torch.from_numpy(a)
print(a)
print(b)

a += 1
print(a)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)


# **Accessing CUDA GPU**

In [26]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to("cuda")
  z = x + y
  print(z)
  # Here you cant convert this tensor to numpy bcoz numpy cant directly access GPU tensors
  # Numpy can access only cpu tensors
  z = z.to("cpu")
  b = z.numpy()
  print(b)



tensor([2., 2., 2., 2., 2.], device='cuda:0')
[2. 2. 2. 2. 2.]


# **Making Gradients**

In [27]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)